### ISSUE TITLE
Error: Text data outside of root node.

### ISSUE THREAD

**Issue by klausb** [ChriD/node-raumkernel#12]
Since an update from March 10 I see the above error with the following stacktrace:

> Error: Text data outside of root node.
Line: 4
Column: 17
Char:
    at error (/root/work/node_modules/sax/lib/sax.js:666:10)
    at strictFail (/root/work/node_modules/sax/lib/sax.js:692:7)
    at SAXParser.write (/root/work/node_modules/sax/lib/sax.js:1035:15)
    at XMLParser.feed (/root/work/node_modules/elementtree/lib/parsers/sax.js:48:15)
    at ElementTree.parse (/root/work/node_modules/elementtree/lib/elementtree.js:271:10)
    at Object.parse (/root/work/node_modules/elementtree/lib/elementtree.js:584:8)
    at parseEvents (/root/work/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:423:16)
    at /root/work/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:340:22
    at ConcatStream.<anonymous> (/root/work/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:91:20)
    at ConcatStream.emit (events.js:188:7)
    at finishMaybe (/root/work/node_modules/readable-stream/lib/_stream_writable.js:513:14)
    at endWritable (/root/work/node_modules/readable-stream/lib/_stream_writable.js:523:3)
    at ConcatStream.Writable.end (/root/work/node_modules/readable-stream/lib/_stream_writable.js:493:41)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:293:19)

**Comment by ChriD** [comment]
Fixed with pull request #13
