### ISSUE TITLE
Dropping all rooms from zone results in error

### ISSUE THREAD

**Issue by Alex9779** [ChriD/node-raumkernel#41]
So I get this error trace when I drop each room with dropRoomFromZone and monitor "rendererStateKeyValueChanged".
I think this is because then there are no zones anymore:
```
TypeError: Cannot read property 'length' of undefined
    at ZoneManager.getRoomObjectFromMediaRendererUdnOrName (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.manager.zoneManager.js:461:93)
    at ZoneManager.getRoomNameForMediaRendererUDN (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.manager.zoneManager.js:391:28)
    at UPNPMediaRendererRaumfeld.roomName (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.raumfeld.js:19:49)
    at Raumkernel.handleEvent (/home/node/.node-red/node_modules/node-red-contrib-raumfeld/nodes/raumfeld-room-play-state-changed.js:18:43)
    at Raumkernel.emit (events.js:164:20)
    at Raumkernel.onRendererStateKeyValueChanged (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.raumkernel.js:268:14)
    at DeviceManager.<anonymous> (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.raumkernel.js:99:158)
    at DeviceManager.emit (events.js:159:13)
    at UPNPMediaRendererRaumfeld.<anonymous> (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.manager.deviceManager.js:452:22)
    at UPNPMediaRendererRaumfeld.emit (events.js:159:13)
    at UPNPMediaRendererRaumfeld.updateRendererStateObject (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.js:152:22)
    at UPNPMediaRendererRaumfeld.updateRendererState (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.js:121:14)
    at UPNPMediaRendererRaumfeld.onRenderingControlSubscription (/home/node/.node-red/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.js:218:14)
    at /home/node/.node-red/node_modules/node-raumkernel/lib/lib.device.upnp.mediaRenderer.js:109:19
    at /home/node/.node-red/node_modules/node-raumkernel/lib/lib.external.upnp-device-client.js:431:13
    at Array.forEach (<anonymous>)
```

**Comment by ChriD** [comment]
fixed it!

**Comment by Alex9779** [comment]
Hmmm your fix is exactly what I did temporarily to test in my env...
👍
